---
address: sandbox.smtp.mailtrap.io
port: '2525'
enable_starttls_auto: true
authentication: login
user_name: db6d06cbc605fe
password: e063937236d4ee
protocol: https
host: https://sandbox.smtp.mailtrap.io
from: from@example.com
